### ISSUE TITLE
No auto refresh

### ISSUE THREAD

**Issue by fourdotone12** [santoru/pihole-dashboard#1]
Hi,

I like the concept so have tried installing it as you describe, however I have an issue.

The display only works when I do ‘sudo pihole-dashboard-draw’ manually.  The cron is not refreshing the display automatically.  Any thoughts?

**Comment by santoru** [comment]
Hi, thank you for the message. 
Can you please verify if you have the cron file `pihole-dashboard-cron` present inside `/etc/cron.d/`? You should have a bunch of files from Pi-Hole already there. Can you also confirm you're using the official `Raspberry Pi OS` distribution?

**Comment by fourdotone12** [comment]
Hello,

Thanks for getting back to me.

This is a new install of Raspbian lite using the official installer.  

I only have php and Pi-hole in the cron.d.  No dashboard file.


Martin.

**Comment by santoru** [comment]
Thank you for the answer.
As a workaround, you can manually copy the cron file inside `/etc/cron.d`.
From the root of the project: 
```bash
cp ./cron/pihole-dashboard-cron /etc/cron.d
```
I'll check this again on a fresh install to see if it's properly installed by PIP.

**Comment by fourdotone12** [comment]
Thank you, works perfectly now.  I think it was just that setup.py didn’t have privilege to write to cron.d.

Thanks again

Martin
