### ISSUE TITLE
modifying code to work with the black/red/white screen (1in13bc)

### ISSUE THREAD

**Issue by jsph6B** [santoru/pihole-dashboard#4]
I attempted to change parts of your code but didnt work. Any ideas on how I could get this working? thanks

**Comment by santoru** [comment]
Hey, I don't support other displays at the moment, you could start by looking at the example for your display here:
https://github.com/waveshare/e-Paper/tree/master/RaspberryPi_JetsonNano/python/examples
and modifying the library calls as needed from your display.

Good luck!
