### ISSUE TITLE
Waveshare 2.13 not drawing

### ISSUE THREAD

**Issue by mrtritop** [santoru/pihole-dashboard#7]
hi, 

i followed your instructions to install everything (Incl. Waveshare etc.). The display is working so far. But after installation of Pihole-Dashboard and rebooting, the display is not drawing. I tried with sudo pihole-dashboard-draw but it didn't work:

```
Traceback (most recent call last):
  File "/usr/local/bin/pihole-dashboard-draw", line 23, in <module>
    pihole_dashboard.update()
  File "/usr/local/lib/python3.9/dist-packages/pihole_dashboard/__init__.py", line 91, in update
    unique_clients = r['unique_clients']
KeyError: 'unique_clients'
```

Anything i could try?

**Comment by santoru** [comment]
Hello, 
What version of PiHole do you have? This could be due to a change on a newer version

Best

**Comment by mrtritop** [comment]
> 

I´m using PiHole 5.12 right now.

**Comment by santoru** [comment]
@mrtritop not sure what the error is here as I can't replicate it, it works on my 5.12 version. I created a new version that should give you more information, can you update the tool to 1.0.2 and see if it prints some details when running it? Thanks

**Comment by santoru** [comment]
Closing due to stale issue
